services:
  postgres:
    image: postgres:16-alpine
    container_name: train-reservation-postgres
    environment:
      POSTGRES_DB: train_reservation
      POSTGRES_USER: train_user
      POSTGRES_PASSWORD: train_password
    ports:
      - "5432:5432"
    volumes:
      - train_postgres_data:/var/lib/postgresql/data

volumes:
  train_postgres_data: